#
# arch/blackfin/mach-bf518/boards/Makefile
#

obj-$(CONFIG_BFIN518F_EZBRD)            += ezbrd.o
obj-$(CONFIG_BFIN518F_TCM)		+= tcm-bf518.o
obj-$(CONFIG_BF518_IPPHONE)             += bf518-ipphone.o
